### PR TITLE
Adding custom 404 page

### PR DESCRIPTION
**Pull request by prabhav**
- Adds a custom 404 page

Took a swing at a custom 404 page — let me know what you think about it and if we need any edits! [Thought the illustration kind of looked like a person trying to look for something with a magnifying glass :)]

[No assigned design] / [Walkthrough](https://www.loom.com/share/71ec9301e87d4885a191812f93d61d22)

Screenshots:

Desktop - 1620px

Tablet - 900px

Mobile - 400px

### CODE REVIEW

**Review by bbqxaxiu — APPROVED** [review]
lgtm! but can you also share with hugh to make sure he likes this design and is ok with it before we merge?

**Comment by prabhav** [comment]
> lgtm! but can you also share with hugh to make sure he likes this design and is ok with it before we merge?

sure thing! i'll go ahead and share with @hhff as well :)

**Comment by hhff** [comment]
@bbqxaxiu @prabhav - approved!

**Comment by prabhav** [comment]
thanks a lot for the review @bbqxaxiu and @hhff! will go ahead and squash and merge!

**Pull request merged**
